import xlwt
import xlrd
import re
cell_txt = open('D:/Cell.txt','r')
lines = cell_txt.readlines()
#新建一个Excel文件
cell = xlwt.Workbook(encoding = 'utf-8', style_compression=0)
#新建一个sheet
cellsheet = cell.add_sheet('My Cell')
cellsheet.write(0,0,'name')
cellsheet.write(0,1,'面积')
cellsheet.write(0,2,'周长')
cellsheet.write(0,3,'似圆度')
cellsheet.write(0,4,'长宽比')
cellsheet.write(0,5,'饱和度')
cellsheet.write(0,6,'长')
cellsheet.write(0,7,'宽')
cellsheet.write(0,8,'asm0')
cellsheet.write(0,9,'con0')
cellsheet.write(0,10,'eng0')
cellsheet.write(0,11,'idm0')
cellsheet.write(0,12,'asm1')
cellsheet.write(0,13,'con1')
cellsheet.write(0,14,'eng1')
cellsheet.write(0,15,'idm1')
cellsheet.write(0,16,'asm2')
cellsheet.write(0,17,'con2')
cellsheet.write(0,18,'eng2')
cellsheet.write(0,19,'idm2')
cellsheet.write(0,20,'asm3')
cellsheet.write(0,21,'con3')
cellsheet.write(0,22,'eng3')
cellsheet.write(0,23,'idm3')
i = 0
for line in lines:
    if line == '\n':
        continue
    i = i + 1
    a = re.split('[：: ]',line)
    # print(a)
    cellsheet.write(i, 0, a[0])
    cellsheet.write(i, 1, float(a[2]))
    cellsheet.write(i, 2, float(a[4]))
    cellsheet.write(i, 3, float(a[6]))
    cellsheet.write(i, 4, float(a[8]))
    cellsheet.write(i, 5, float(a[10]))
    cellsheet.write(i, 6, float(a[12]))
    cellsheet.write(i, 7, float(a[14]))
    cellsheet.write(i, 8, float(a[16]))
    cellsheet.write(i, 9, float(a[17]))
    cellsheet.write(i, 10, float(a[18]))
    cellsheet.write(i, 11, float(a[19]))
    cellsheet.write(i, 12, float(a[21]))
    cellsheet.write(i, 13, float(a[22]))
    cellsheet.write(i, 14, float(a[23]))
    cellsheet.write(i, 15, float(a[24]))
    cellsheet.write(i, 16, float(a[26]))
    cellsheet.write(i, 17, float(a[27]))
    cellsheet.write(i, 18, float(a[28]))
    cellsheet.write(i, 19, float(a[29]))
    cellsheet.write(i, 20, float(a[31]))
    cellsheet.write(i, 21, float(a[32]))
    cellsheet.write(i, 22, float(a[33]))
    cellsheet.write(i, 23, float(a[34]))

    # for i in range(1, 7):
    #     b = a[i].split(' ')
    #     print(b)
cell.save('Excel_cell.xls')